pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build
      - 'title~=^build\(deps-dev\): bump '
    actions:
      merge:
        method: merge
