name: Assign Reviewer
on: pull_request_target

permissions:
  pull-requests: write

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Assign reviewer
        if: >
          github.actor != 'dependabot[bot]'
          && startsWith(github.event.pull_request.title, 'build(deps-dev): bump ') == false
          && contains(github.event.action, 'opened')
        run: >
          gh pr edit ${{ github.event.number }}
          --add-assignee ${{ github.event.pull_request.user.login }}
          --add-reviewer remarkablemark
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
