name: auto-assign
on: pull_request_target

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' && endsWith(github.actor, '[bot]') == false

    steps:
      - name: Auto assign
        run: gh pr edit ${{ github.event.pull_request.html_url }} --add-assignee ${{ github.event.pull_request.user.login }} --add-reviewer remarkablemark
        env:
          GITHUB_TOKEN: ${{ github.token }}
